services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: insightfuse
      POSTGRES_PASSWORD: insightfuse123
      POSTGRES_DB: insightfuse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insightfuse"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://insightfuse:insightfuse123@postgres:5432/insightfuse
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: python run.py

volumes:
  postgres_data: